theme: minima

title: twinkle media
author: CEO twinkle media
email: ceo@twinklemedia.com
description: > # this means to ignore newlines until "baseurl:"
  twinkle media will keep the twinkle in your clients' eye!! 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
